# config/constants.py
"""
Constantes de datos de la aplicación
"""

CIUDADES = [
    "ABA BARRANQUILLA AEROPUER", "ABG BUCARAMANGA AEROPUER", "ADZ SAN ANDRES",
    "AEJ BARRANCABERMEJA AERO", "AIB IBAGUE AEROPUERTO", "ALM ALAMOS",
    "AMT MONTERIA AEROPUERTO", "ANV NEIVA AEROPUERTO", "APA PALMIRA AEROPUERTO",
    "APE PEREIRA AEROPUERTO", "APO APARTADO", "APS PASTO AEROPUERTO",
    "ARC RIOHACHA AEROPUERTO", "ARN RIONEGRO AEROPUERTO",
    "ASM SANTA MARTA AEROPUER", "ATC TUMACO AEROPUERTO",
    "AVU VALLEDUPAR AEROPUERT", "AXM ARMENIA", "BAQ BARRANQUILLA",
    "BGA BUCARAMANGA", "BGG BUGA", "BOG BOGOTA", "BUN BUENAVENTURA",
    "CAQ CAUCASIA", "CGW CARTAGO", "CLO CALI", "CNG CIENAGA", "CTG CARTAGENA",
    "CUC CUCUTA", "CZL COROZAL", "DTA DUITAMA", "EJA BARRANCABERMEJ",
    "EYP EL YOPAL", "FLA FLORENCIA", "GIR GIRARDOT", "HDA HONDA", "IBE IBAGUE",
    "IPI IPIALES", "LDR LA DORADA", "LET LETICIA", "MAQ MARIQUITA", "MCO MAICAO",
    "MDE MEDELLIN", "MTR MONTERIA", "MZL MANIZALES", "NVA NEIVA", "PAL PAMPLONA",
    "PAM PALMIRA", "PEI PEREIRA", "PPN POPAYAN", "PSO PASTO", "PTO PUERTO BOYACA",
    "RCH RIOHACHA", "RNG RIONEGRO", "RZG REZAGOS", "SIJ SINCELEJO", "SMR SANTA MARTA",
    "SOX SOGAMOSO", "STQ SANTANDER DE QUILICH", "TCO TUMACO –", "TNB TUNJA",
    "UIB QUIDBO", "ULQ TULUA", "VUP VALLEDUPAR", "WC VILLAVICENCIO", "000 CENTRAL",
    "900 LOGISTICA INTERNACIO", "901 BODEGA MIAMI", "999 TODAS LAS PLAZAS"
]

TIPOS_INCIDENCIA = ["22", "27", "50", "51", "52", "920", "929"]

# Mensajes de error
ERROR_MESSAGES = {
    'NO_SESSION': 'Debe iniciar sesión para continuar',
    'NO_AMPLIACION': 'El campo de ampliación está vacío',
    'NO_FILE': 'No se ha seleccionado ningún archivo',
    'NO_GUIAS': 'El archivo Excel no contiene guías',
    'LOGIN_FAILED': 'Error en el inicio de sesión',
    'NAVIGATION_FAILED': 'Error en la navegación'
}